/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.parth;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static org.apache.derby.iapi.reference.ClassName.ResultSet;

/**
 *
 * @author Zarna
 */
public class Order extends javax.swing.JFrame {

    /**
     * Creates new form Order
     */
    public Order() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        chesseBurger = new javax.swing.JTextField();
        chatpataAloo = new javax.swing.JTextField();
        NaanAloo = new javax.swing.JTextField();
        puffVeggie = new javax.swing.JTextField();
        FrenchFries = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Chatpatanaan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Veg. Chesse Burger");

        jLabel5.setText("Grilled chatpata aloo");

        jLabel6.setText("Chatpata Naan Aloo");

        jLabel7.setText("Pizza Mc Puff +Mc Veggie");

        jLabel8.setText("French_Fries");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Name");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Price");

        jLabel2.setText("50");

        jLabel3.setText("51");

        jLabel10.setText("64");

        jLabel11.setText("106");

        jLabel12.setText("60");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Qty.");

        chesseBurger.setColumns(3);
        chesseBurger.setText("0");

        chatpataAloo.setText("0");
        chatpataAloo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatpataAlooActionPerformed(evt);
            }
        });

        NaanAloo.setText("0");
        NaanAloo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NaanAlooActionPerformed(evt);
            }
        });

        puffVeggie.setText("0");

        FrenchFries.setText("0");
        FrenchFries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrenchFriesActionPerformed(evt);
            }
        });

        jLabel14.setText("Chatpatanaan");

        jLabel15.setText("60");

        Chatpatanaan.setText("0");
        Chatpatanaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChatpatanaanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addComponent(jLabel9))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel2)
                                .addGap(145, 145, 145))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel15)))
                                .addGap(139, 139, 139)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chatpataAloo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NaanAloo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(puffVeggie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FrenchFries, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(chesseBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Chatpatanaan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(submit)
                        .addGap(100, 100, 100)
                        .addComponent(jButton2)))
                .addGap(33, 33, 33))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Chatpatanaan, FrenchFries, NaanAloo, chatpataAloo, chesseBurger, puffVeggie});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel1)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(chesseBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(chatpataAloo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(NaanAloo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(puffVeggie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(FrenchFries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(Chatpatanaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chatpataAlooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatpataAlooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chatpataAlooActionPerformed

    private void NaanAlooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NaanAlooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NaanAlooActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
                // TODO add your handling code here:
            CustomerBill cus=new CustomerBill();
            Connection con;
            int id=0,total=0;
            int cb=0,ca=0,mp=0,mv=0,mct=0,f=0,chnan=0;
            int A=0,B=0,C=0,D=0,E=0,F=0;
            Statement st;
             ResultSet r;
            try {
                cb=Integer.parseInt(chesseBurger.getText());
                ca=Integer.parseInt(chatpataAloo.getText());
                mp=Integer.parseInt(NaanAloo.getText());
                mv=Integer.parseInt(puffVeggie.getText());
                f=Integer.parseInt(FrenchFries.getText());
                chnan=Integer.parseInt(Chatpatanaan.getText());
            }
            catch(Exception e){
                 JOptionPane.showMessageDialog(this,"Please Enter Valid Number","Error",JOptionPane.ERROR_MESSAGE);     
            }
          
        try {
            con=DriverManager.getConnection("jdbc:derby://localhost:1527/Food_Information","root","root");
            System.out.print("Connection Created");
            st=con.createStatement();
            r=st.executeQuery("select * from FOOD_INFORMATION");
            while(r.next()) {
                if(r.getInt("ID")==1) {
                    total+=cb*r.getInt("PRICE");
                    A=r.getInt("PRICE");
                }
                if(r.getInt("ID")==2) {
                    total+=ca*r.getInt("PRICE");
                    B=r.getInt("PRICE");
                }
                if(r.getInt("ID")==3) {
                    total+=mp*r.getInt("PRICE");
                    C=r.getInt("PRICE");
                }
                if(r.getInt("ID")==4) {
                    total+=mv*r.getInt("PRICE");
                    D=r.getInt("PRICE");
                }
                if(r.getInt("ID")==5) {
                    total+=f*r.getInt("PRICE");
                    E=r.getInt("PRICE");
                }
                if(r.getInt("ID")==6) {
                    total+=chnan*r.getInt("PRICE");
                    F=r.getInt("PRICE");;
                }
                
            }
            System.out.print(total);
            
            
            
            
           ResultSet rs=st.executeQuery("select * from ID");
            while(rs.next())
                id=rs.getInt(2);
            String str="UPDATE ID SET VALUE="+(id+1)+"WHERE ID=1";
            st.executeUpdate(str);
            cus.setId(id);
            cus.setChatpatanaan(chnan);
            cus.setChatpatanaanaloo(mp);
            cus.setFrenchfries(f);
            cus.setGrilledchatpataaloo(ca);
            cus.setPizzamcpuffandmcveggie(mv);
            cus.setVegchesseburger(cb);
            cus.setTotalamount(total);
            
            if(total!=0) {
                billAddManager b=new billAddManager();
                b.insert(cus);
                b.close();
            }
            st=con.createStatement();
            rs=st.executeQuery("select * from customer_bill where id="+id);
           
            System.out.println("ITEM\t\t\t\t"+"\tQTY\t"+"\tPRICE");
             System.out.println();
            while(rs.next()) {
                if(rs.getInt(2)!=0) 
                    System.out.println("VEGCHESSE BURGER\t\t\t"+rs.getInt(2)+"\t\t"+A*rs.getInt(2));
                if(rs.getInt(3)!=0) 
                    System.out.println("GRILLED CHATPATA AALOO\t\t\t"+rs.getInt(3)+"\t\t"+B*rs.getInt(3));
                if(rs.getInt(4)!=0) 
                    System.out.println("CHATPATA NAAN AALOO\t\t\t"+rs.getInt(4)+"\t\t"+C*rs.getInt(4));
                if(rs.getInt(5)!=0) 
                    System.out.println("PIZZA MC PUFF + MCVEGGIE\t\t"+rs.getInt(5)+"\t\t"+D*rs.getInt(5));
                if(rs.getInt(6)!=0) 
                    System.out.println("FRENCH FRIES\t\t\t\t"+rs.getInt(6)+"\t\t"+E*rs.getInt(6));
                if(rs.getInt(7)!=0) 
                    System.out.println("CHATPATA NAAN\t\t\t\t"+rs.getInt(7)+"\t\t"+F*rs.getInt(7));
                if(rs.getInt(8)!=0) 
                    System.out.println("\t\t\tTOTAL:"+"\t\t\t\t"+rs.getInt(8));
            }
            
            /*Document pdf=new Document();
            while(rs.next())
                try {
                    PdfWriter.getInstance(pdf, new FileOutputStream("bill.pdf"));
                    pdf.open();
                    PdfPTable pt=new PdfPTable(3);
                    PdfPCell tc;
                    tc=new PdfPCell(new Phrase(rs.getInt(2)));
                    pt.addCell(tc);
                    pdf.add(tc);
                    pdf.close();
                    
                } catch (DocumentException ex) {
                    Logger.getLogger(Order.class.getName()).log(Level.SEVERE, null, ex);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Order.class.getName()).log(Level.SEVERE, null, ex);
                }*/
                
                
                
            
            
        } catch (SQLException ex) {
            
            Logger.getLogger(Order.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_submitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        chesseBurger.setText("0");
        chatpataAloo.setText("0");
        NaanAloo.setText("0");
        puffVeggie.setText("0");
        FrenchFries.setText("0");
        Chatpatanaan.setText("0");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void FrenchFriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrenchFriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FrenchFriesActionPerformed

    private void ChatpatanaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChatpatanaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChatpatanaanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Chatpatanaan;
    private javax.swing.JTextField FrenchFries;
    private javax.swing.JTextField NaanAloo;
    private javax.swing.JTextField chatpataAloo;
    private javax.swing.JTextField chesseBurger;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField puffVeggie;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
