/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.parth;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Zarna
 */
public class Search_Bill extends javax.swing.JFrame {

    /**
     * Creates new form Search_Bill
     */
    public Search_Bill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Id = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bill_Id:");

        Id.setColumns(3);
        Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdActionPerformed(evt);
            }
        });

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1)
                        .addGap(67, 67, 67)
                        .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(SearchButton)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SearchButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        try {
            Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/Food_Information","root","root");
            Statement st=con.createStatement();
            ResultSet r;
            int vcb=0,gca=0,cna=0,ppv=0,ff=0,cn=0;
            ResultSet rs=st.executeQuery("SELECT * FROM food_information");
            while(rs.next()){
                if(rs.getInt(1)==1)
                    vcb=rs.getInt(3);
                if(rs.getInt(1)==2)
                    gca=rs.getInt(3);
                if(rs.getInt(1)==3)
                    cna=rs.getInt(3);
                
                if(rs.getInt(1)==4)
                    ppv=rs.getInt(3);
                
                if(rs.getInt(1)==5)
                    ff=rs.getInt(3);
                if(rs.getInt(1)==6)
                    cn=rs.getInt(3);
            }
            int id=0;
            
            
            rs=st.executeQuery("select * from customer_bill where id="+Integer.parseInt(Id.getText()));
           
            System.out.println("ITEM\t\t\t\t"+"\tQTY\t"+"\tPRICE");
             System.out.println();
            while(rs.next()) {
                if(rs.getInt(2)!=0) 
                    System.out.println("VEGCHESSE BURGER\t\t\t"+rs.getInt(2)+"\t\t"+vcb*rs.getInt(2));
                if(rs.getInt(3)!=0) 
                    System.out.println("GRILLED CHATPATA AALOO\t\t\t"+rs.getInt(3)+"\t\t"+gca*rs.getInt(3));
                if(rs.getInt(4)!=0) 
                    System.out.println("CHATPATA NAAN AALOO\t\t\t"+rs.getInt(4)+"\t\t"+cna*rs.getInt(4));
                if(rs.getInt(5)!=0) 
                    System.out.println("PIZZA MC PUFF + MCVEGGIE\t\t"+rs.getInt(5)+"\t\t"+ppv*rs.getInt(5));
                if(rs.getInt(6)!=0) 
                    System.out.println("FRENCH FRIES\t\t\t\t"+rs.getInt(6)+"\t\t"+ff*rs.getInt(6));
                if(rs.getInt(7)!=0) 
                    System.out.println("CHATPATA NAAN\t\t\t\t"+rs.getInt(7)+"\t\t"+cn*rs.getInt(7));
                if(rs.getInt(8)!=0) 
                    System.out.println("\t\t\tTOTAL:"+"\t\t\t\t"+rs.getInt(8));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Search_Bill.class.getName()).log(Level.SEVERE, null, ex);
           
        }
        
           
    }//GEN-LAST:event_SearchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search_Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Id;
    private javax.swing.JButton SearchButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
